apiVersion: apps/v1
kind: Deployment
metadata:
  name: springboot-hello
  labels:
    app: hello
spec:
  replicas: 3
  selector:
    matchLabels:
      app: hello
  template:
    metadata:
      labels:
        app: hello
    spec:
      containers:
      - name: hello
        image: springboot-hello
        ports:
        - containerPort: 9009