
server:
  port: 9037

spring:
  application:
    name: spring-hystrix-feign
eureka:
  instance:
    namespace: ${spring.application.name}
  client:
    service-url:
      defaultZone: http://localhost:9030/eureka
    fetch-registry: true
    register-with-eureka: true

