spring:
  application:
    name: @name@
  redis:
    jedis:
      pool:
        max-idle: 8
        min-idle: 4
        max-active: 8
    database: 0
    host: 192.168.1.5
    port: 6379
    connect-timeout: 2000
  profiles:
    active: dev

server:
  port: 9019