spring:
  application:
    name: @name@
  datasource:
    hikari:
      pool-name: HikariCP
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:8066/TESTDB?zeroDateTimeBehavior=convertToNull&characterEncoding=utf8
    username: root
    password: 123456
server:
  port: 9016

jackson:
  date-format: yyyy-MM-dd HH:mm:ss
  time-zone: GMT+8
  serialization:
    write-dates-as-timestamps: false

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    auto-mapping-behavior: full
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath*:mapper/**/*Mapper.xml
  global-config:
    # 逻辑删除配置
    db-config:
      # 删除前
      logic-not-delete-value: 1
      # 删除后
      logic-delete-value: 0

logging:
  level:
    root: info
    cn.com.sk.rocketmq: debug
